"""Generate the homepage's static vector globe from Natural Earth's public-domain land data.

Usage: python3 scripts/generate-network-globe.py /path/to/ne_110m_land.geojson
Source: https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_110m_land.geojson
"""
import json
import math
import random
import sys
from pathlib import Path

source = json.loads(Path(sys.argv[1]).read_text())
polygons = []
for feature in source['features']:
    geometry = feature['geometry']
    groups = [geometry['coordinates']] if geometry['type'] == 'Polygon' else geometry['coordinates']
    for rings in groups:
        ring = rings[0]
        polygons.append((min(p[0] for p in ring), max(p[0] for p in ring), min(p[1] for p in ring), max(p[1] for p in ring), ring))

def is_land(lon, lat):
    for min_x, max_x, min_y, max_y, ring in polygons:
        if not (min_x <= lon <= max_x and min_y <= lat <= max_y):
            continue
        inside = False
        previous = ring[-1]
        for point in ring:
            if (point[1] > lat) != (previous[1] > lat) and lon < (previous[0] - point[0]) * (lat - point[1]) / (previous[1] - point[1]) + point[0]:
                inside = not inside
            previous = point
        if inside:
            return True
    return False

def project(lon, lat):
    a, b, tilt = math.radians(lon + 28), math.radians(lat), math.radians(16)
    x = math.cos(b) * math.sin(a)
    y = math.cos(tilt) * math.sin(b) - math.sin(tilt) * math.cos(b) * math.cos(a)
    z = math.sin(tilt) * math.sin(b) + math.cos(tilt) * math.cos(b) * math.cos(a)
    return 300 + 254*x, 294 - 254*y, z

parts = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 620" fill="none">',
         '<!-- Land geometry: Natural Earth, public domain. Generated by scripts/generate-network-globe.py. -->',
         '<defs><radialGradient id="glow"><stop stop-color="#00d994" stop-opacity=".05"/><stop offset="1" stop-color="#00d994" stop-opacity="0"/></radialGradient></defs>',
         '<circle cx="300" cy="294" r="286" fill="url(#glow)"/>']
# Quiet dotted latitude/longitude lines give the ocean a spherical surface.
for axis in ('latitude', 'longitude'):
    for fixed in range(-180 if axis == 'longitude' else -75, 180 if axis == 'longitude' else 90, 15):
        dots = []
        for step in range(-180 if axis == 'latitude' else -90, 181 if axis == 'latitude' else 91, 2):
            x, y, z = project(step if axis == 'latitude' else fixed, fixed if axis == 'latitude' else step)
            if z > 0:
                dots.append(f'M{x:.1f},{y:.1f}h.1')
        parts.append(f'<path d="{"".join(dots)}" stroke="#009f78" stroke-width=".8" stroke-linecap="round" opacity=".28"/>')
groups = [[] for _ in range(5)]
random.seed(17)
for row in range(180):
    lat = -80 + row * .92
    if lat > 85:
        break
    count = max(1, round(390 * math.cos(math.radians(lat))))
    for column in range(count):
        lon = -180 + (column + (row % 2) * .5) * 360 / count + random.uniform(-.24, .24)
        point_lat = lat + random.uniform(-.24, .24)
        x, y, z = project(lon, point_lat)
        if z <= 0 or not is_land(lon, point_lat):
            continue
        groups[min(4, int(z * 5))].append(f'M{x:.1f},{y:.1f}h.1')
for index, dots in enumerate(groups):
    parts.append(f'<path d="{"".join(dots)}" stroke="#00d69a" stroke-width="{1+index*.1:.2f}" stroke-linecap="round" opacity="{.35+index*.1:.2f}"/>')
parts.append('<circle cx="300" cy="294" r="254" stroke="#00c78e" stroke-opacity=".32" stroke-dasharray="1 6"/>')
for x, y in [(88,62),(47,223),(79,463),(431,20),(572,311),(596,377),(563,481),(313,207)]:
    parts.append(f'<path d="M{x-7} {y}h14M{x} {y-7}v14" stroke="#00bc88" stroke-width=".8" opacity=".45"/>')
parts.append('</svg>')
output = Path(__file__).resolve().parents[1] / 'public' / 'network-globe.svg'
output.write_text(''.join(parts))
print(f'Generated {output.name}: {sum(map(len, groups))} land points, {output.stat().st_size} bytes')
